services:
  mongodb:
    image: mongo:8.0
    container_name: usp_mongo_test
    restart: unless-stopped
    volumes:
      - mongo_data_test:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'usp-backend-test'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usp_app_test
    command: npm run test
    environment:
      NODE_ENV: test
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/usp-backend-test
    depends_on:
      - mongodb

volumes:
  mongo_data_test:
