services:
  mongodb:
    image: mongo:8.0
    container_name: usp_mongo_prod
    restart: unless-stopped
    volumes:
      - mongo_data_prod:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'usp-backend-prod'
    networks:
      - usp_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usp_app_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/usp-backend-prod
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - usp_network

volumes:
  mongo_data_prod:

networks:
  usp_network:
    driver: bridge
