services:
  mongodb:
    image: mongo:8.0
    container_name: usp_mongo_dev
    restart: unless-stopped
    volumes:
      - mongo_data_dev:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'usp-backend-dev'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usp_app_dev
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/usp-backend-dev
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

volumes:
  mongo_data_dev:
