// File: src/swagger/schemas/adminProgrammeSchemas.ts
import { OpenAPIV3 } from 'openapi-types';

export const adminProgrammeSchemas: OpenAPIV3.ComponentsObject['schemas'] = {
  CreateProgrammeRequest: {
    type: 'object',
    properties: {
      universityId: {
        type: 'string',
        example: '60d0fe4f5311236168a109ca',
        description: 'ID of the university offering this programme',
      },
      name: { type: 'string', example: 'Bachelor of Computer Science' },
      description: {
        type: 'string',
        example: 'A four-year undergraduate programme in computer science.',
      },
      type: {
        type: 'string',
        enum: [
          'bachelor',
          'master',
          'phd',
          'associate',
          'diploma',
          'certificate',
          'exchange',
          'foundation',
          'executive',
        ],
      },
      subjectArea: {
        type: 'string',
        enum: [
          'computer_science',
          'engineering',
          'business',
          'agriculture',
          'arts',
          'education',
          'law',
          'medicine',
          'social_sciences',
          'natural_sciences',
          'environmental_science',
          'mathematics',
          'economics',
          'design',
          'media',
          'philosophy',
          'psychology',
          'international_relations',
          'data_science',
        ],
      },
      durationSemesters: { type: 'integer', example: 8 },
      startDate: { type: 'string', format: 'date', example: '2025-09-01' },
      endDate: { type: 'string', format: 'date', example: '2029-05-31' },
      tuitionFee: { type: 'string', example: 'CAD 15000' },
      applicationFee: { type: 'string', example: 'CAD 150' },
      intakes: {
        type: 'array',
        items: { type: 'string', example: 'Fall 2025' },
      },
      modules: {
        type: 'array',
        items: { type: 'string', example: 'Data Structures' },
      },
      entryRequirements: {
        type: 'array',
        items: { type: 'string', example: 'High School Diploma' },
      },
      services: {
        type: 'array',
        items: { type: 'string', example: 'Library Access' },
      },
      images: {
        type: 'array',
        items: { type: 'string', format: 'binary' },
        description: 'One or more image files',
      },
    },
    required: [
      'universityId',
      'name',
      'type',
      'subjectArea',
      'durationSemesters',
      'startDate',
      'tuitionFee',
      'modules',
      'entryRequirements',
    ],
  },

  UpdateProgrammeRequest: {
    type: 'object',
    properties: {
      universityId: { type: 'string' },
      name: { type: 'string' },
      description: { type: 'string' },
      type: {
        type: 'string',
        enum: [
          'bachelor',
          'master',
          'phd',
          'associate',
          'diploma',
          'certificate',
          'exchange',
          'foundation',
          'executive',
        ],
      },
      subjectArea: {
        type: 'string',
        enum: [
          'computer_science',
          'engineering',
          'business',
          'agriculture',
          'arts',
          'education',
          'law',
          'medicine',
          'social_sciences',
          'natural_sciences',
          'environmental_science',
          'mathematics',
          'economics',
          'design',
          'media',
          'philosophy',
          'psychology',
          'international_relations',
          'data_science',
        ],
      },
      durationSemesters: { type: 'integer' },
      startDate: { type: 'string', format: 'date' },
      endDate: { type: 'string', format: 'date' },
      tuitionFee: { type: 'string' },
      applicationFee: { type: 'string' },
      intakes: { type: 'array', items: { type: 'string' } },
      modules: { type: 'array', items: { type: 'string' } },
      entryRequirements: { type: 'array', items: { type: 'string' } },
      services: { type: 'array', items: { type: 'string' } },
      images: {
        type: 'array',
        items: { type: 'string', format: 'binary' },
      },
    },
  },

  Programme: {
    type: 'object',
    properties: {
      id: { type: 'string', example: '60d0fe4f5311236168a109cb' },
      universityId: {
        type: 'string',
        example: '60d0fe4f5311236168a109ca',
      },
      name: { type: 'string', example: 'Bachelor of Computer Science' },
      description: {
        type: 'string',
        example: 'A four-year undergraduate programme in computer science.',
      },
      type: {
        type: 'string',
        enum: [
          'bachelor',
          'master',
          'phd',
          'associate',
          'diploma',
          'certificate',
          'exchange',
          'foundation',
          'executive',
        ],
      },
      subjectArea: {
        type: 'string',
        enum: [
          'computer_science',
          'engineering',
          'business',
          'agriculture',
          'arts',
          'education',
          'law',
          'medicine',
          'social_sciences',
          'natural_sciences',
          'environmental_science',
          'mathematics',
          'economics',
          'design',
          'media',
          'philosophy',
          'psychology',
          'international_relations',
          'data_science',
        ],
      },
      durationSemesters: { type: 'integer', example: 8 },
      startDate: { type: 'string', format: 'date', example: '2025-09-01' },
      endDate: { type: 'string', format: 'date', example: '2029-05-31' },
      tuitionFee: { type: 'string', example: 'CAD 15000' },
      applicationFee: { type: 'string', example: 'CAD 150' },
      intakes: {
        type: 'array',
        items: { type: 'string', example: 'Fall 2025' },
      },
      modules: {
        type: 'array',
        items: { type: 'string', example: 'Data Structures' },
      },
      entryRequirements: {
        type: 'array',
        items: { type: 'string', example: 'High School Diploma' },
      },
      services: {
        type: 'array',
        items: { type: 'string', example: 'Library Access' },
      },
      images: {
        type: 'array',
        items: {
          type: 'string',
          format: 'uri',
          example: 'https://s3.aws/.../img.png',
        },
      },
      createdAt: {
        type: 'string',
        format: 'date-time',
        example: '2025-04-18T12:00:00Z',
      },
      updatedAt: {
        type: 'string',
        format: 'date-time',
        example: '2025-04-18T12:30:00Z',
      },
    },
  },

  PaginatedProgrammes: {
    type: 'object',
    properties: {
      programmes: {
        type: 'array',
        items: { $ref: '#/components/schemas/Programme' },
      },
      totalPages: { type: 'integer', example: 5 },
      currentPage: { type: 'integer', example: 1 },
    },
  },
};
